services:
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    entrypoint: ./.docker/api/entrypoint.sh
    container_name: api
    volumes:
      - '.:/home/node/app'
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - api-net
    mem_limit: 2g

  db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    container_name: db
    volumes:
      - './db/postgres:/var/lib/postgresql/data'
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gac
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5050:5050'
    networks:
      - api-net
    mem_limit: 1g

networks:
  api-net:
    driver: bridge
