FROM node:23.10.0-alpine3.21

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

COPY --chown=node:node . .

CMD ["npm", "run", "start:debug"]